blank_issues_enabled: false

contact_links:
  - name: Documentation
    url: https://github.com/Shivam-899/engineering-playbook
    about: Please check the documentation before opening an issue.

  - name: Discussions
    url: https://github.com/Shivam-899/engineering-playbook/discussions
    about: Ask questions or discuss ideas here.